# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/sirinejrad/cypress-cucumber.git'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.     
      npm install  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npx cypress run'

- script: |
    npm install
    npx cypress run
  displayName: 'npm install, and npx cypress run'
